GET http://localhost:3000/product

###

POST http://localhost:3000/items

content-type: application/json
body:
{
    "page": 1, 
    "quantityPerPage" : 3,
    "type" : "ladies", 
    "productGroup" : "Đầm"
}